parameters:
    musement_api_client.api_configuration:
        version: 'v3'
        base_url: 'https://api.musement.com/api'
        cities_endpoint: '/cities'
    musement_api_client.requests_headers:
        X-Musement-Version: '3.4.0'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tui\Musement\ApiClient\Infrastructure\Client\Http\HttpClient:
        class: Tui\Musement\ApiClient\Infrastructure\Client\Http\HttpClient
        arguments:
            $apiConfiguration: '%musement_api_client.api_configuration%'
            $requestsHeaders: '%musement_api_client.requests_headers%'

    Tui\Musement\ApiClient\Infrastructure\Client\Http\:
        resource: '../../Infrastructure/Client/Http/*/'

    Tui\Musement\ApiClient\Domain\:
        resource: '../../Domain/*/Service/'